const $=s=>document.querySelector(s), fmt=n=>n==null?'—':Number(n).toLocaleString('ja-JP');
const els={key:$('#apiKey'),input:$('#videoInput'),interval:$('#interval'),start:$('#start'),stop:$('#stop'),card:$('#liveCard'),title:$('#title'),channel:$('#channel'),thumb:$('#thumb'),status:$('#status'),current:$('#current'),peak:$('#peak'),avg:$('#avg'),elapsed:$('#elapsed'),samples:$('#samples'),canvas:$('#chart'),history:$('#history'),gap:$('#gap'),net:$('#net'),precisionDuration:$('#precisionDuration'),precisionStart:$('#precisionStart'),precisionStop:$('#precisionStop'),precisionBadge:$('#precisionBadge'),precisionCountdown:$('#precisionCountdown'),quota:$('#quota')};
let timer=null, active=null, lastTick=0, precisionUntil=0, precisionTicker=null, apiCalls=0;
els.key.value=localStorage.getItem('yt_api_key')||''; els.interval.value=localStorage.getItem('yt_interval')||'30';
function idFrom(v){v=v.trim(); if(/^[\w-]{11}$/.test(v))return v; try{let u=new URL(v);if(u.hostname.includes('youtu.be'))return u.pathname.split('/')[1];if(u.searchParams.get('v'))return u.searchParams.get('v');let p=u.pathname.split('/').filter(Boolean);if(['live','shorts','embed'].includes(p[0]))return p[1]}catch{} return null}
function load(){return JSON.parse(localStorage.getItem('live_logs')||'{}')} function saveAll(x){localStorage.setItem('live_logs',JSON.stringify(x))} function save(){if(!active)return;let x=load();x[active.id]=active;saveAll(x);renderHistory()}
async function fetchVideo(id){apiCalls++;updateQuota();let key=els.key.value.trim();if(!key)throw Error('APIキーを入力してください。');let url=`https://www.googleapis.com/youtube/v3/videos?part=snippet,liveStreamingDetails&id=${encodeURIComponent(id)}&key=${encodeURIComponent(key)}`;let r=await fetch(url);let j=await r.json();if(!r.ok)throw Error(j.error?.message||'YouTube APIエラー');if(!j.items?.length)throw Error('動画が見つかりません。');return j.items[0]}
function newLog(v){let l=v.liveStreamingDetails||{};return{id:v.id,title:v.snippet.title,channel:v.snippet.channelTitle,thumb:v.snippet.thumbnails?.medium?.url||'',actualStartTime:l.actualStartTime||null,createdAt:new Date().toISOString(),endedAt:null,points:[]}}
function currentIntervalMs(){return precisionUntil>Date.now()?1000:Number(els.interval.value)*1000}
function scheduleNext(delay=currentIntervalMs()){clearTimeout(timer);if(active&&!active.endedAt)timer=setTimeout(async()=>{await tick();scheduleNext()},delay)}
function updateQuota(){if(els.quota)els.quota.textContent=`API取得 ${apiCalls.toLocaleString('ja-JP')}回（概算 ${apiCalls.toLocaleString('ja-JP')} units）`}
function updatePrecisionUI(){let remain=Math.max(0,precisionUntil-Date.now());if(remain>0){let sec=Math.ceil(remain/1000),m=Math.floor(sec/60),s=sec%60;els.precisionCountdown.textContent=`精密記録 残り ${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;els.precisionCountdown.classList.add('active');els.precisionBadge.textContent='1秒記録中';els.precisionBadge.classList.add('on');els.precisionStart.classList.add('hidden');els.precisionStop.classList.remove('hidden')}else{if(precisionUntil){precisionUntil=0;clearInterval(precisionTicker);precisionTicker=null;if(timer&&active&&!active.endedAt)scheduleNext(0)}els.precisionCountdown.textContent=`通常 ${els.interval.options[els.interval.selectedIndex].text}間隔`;els.precisionCountdown.classList.remove('active');els.precisionBadge.textContent='通常記録';els.precisionBadge.classList.remove('on');els.precisionStart.classList.remove('hidden');els.precisionStop.classList.add('hidden')}}
function startPrecision(){if(!active||!timer)return alert('先にライブの記録を開始してください。');let seconds=Number(els.precisionDuration.value);precisionUntil=Date.now()+seconds*1000;updatePrecisionUI();clearInterval(precisionTicker);precisionTicker=setInterval(updatePrecisionUI,250);scheduleNext(0)}
function stopPrecision(){precisionUntil=0;clearInterval(precisionTicker);precisionTicker=null;updatePrecisionUI();if(timer&&active&&!active.endedAt)scheduleNext(0)}
async function tick(){if(!active)return;try{let v=await fetchVideo(active.id),l=v.liveStreamingDetails||{},now=Date.now(),interval=currentIntervalMs();if(lastTick&&now-lastTick>Math.max(interval*2.5,3000)){els.gap.textContent=`バックグラウンド等により約${Math.round((now-lastTick)/1000)}秒の記録空白が発生しました。`;els.gap.classList.remove('hidden')}lastTick=now;if(l.concurrentViewers!=null){active.points.push({t:new Date().toISOString(),viewers:Number(l.concurrentViewers),intervalSeconds:interval/1000,precision:precisionUntil>now});active.title=v.snippet.title;active.channel=v.snippet.channelTitle;active.thumb=v.snippet.thumbnails?.medium?.url||active.thumb;save();render()}else if(l.actualEndTime){active.endedAt=l.actualEndTime;save();render();stop(false);els.status.textContent='終了';els.status.classList.remove('live')}else{els.net.textContent='同接非公開 / 待機中'} }catch(e){els.net.textContent='取得エラー';console.error(e)}}
async function start(){let id=idFrom(els.input.value);if(!id)return alert('有効なYouTube URLまたは動画IDを入力してください。');localStorage.setItem('yt_api_key',els.key.value.trim());localStorage.setItem('yt_interval',els.interval.value);try{els.start.disabled=true;apiCalls=0;updateQuota();let v=await fetchVideo(id),l=v.liveStreamingDetails;if(!l)throw Error('この動画はライブ配信ではありません。');let old=load()[id];active=old&&!old.endedAt?old:newLog(v);els.card.classList.remove('hidden');els.stop.disabled=false;lastTick=0;await tick();if(active&&!active.endedAt){scheduleNext();els.net.textContent='記録中';els.status.textContent='LIVE';els.status.classList.add('live');updatePrecisionUI()}}catch(e){alert(e.message);els.start.disabled=false}}
function stop(manual=true){clearTimeout(timer);timer=null;precisionUntil=0;clearInterval(precisionTicker);precisionTicker=null;updatePrecisionUI();if(manual&&active){active.manualStoppedAt=new Date().toISOString();save()}els.stop.disabled=true;els.start.disabled=false;els.net.textContent=manual?'停止中':'配信終了'}
function stats(){let p=active?.points||[];if(!p.length)return{peak:null,avg:null};let a=p.map(x=>x.viewers);return{peak:Math.max(...a),avg:Math.round(a.reduce((x,y)=>x+y,0)/a.length)}}
function duration(ms){let s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor(s%3600/60),q=s%60;return `${h}:${String(m).padStart(2,'0')}:${String(q).padStart(2,'0')}`}
function render(){if(!active)return;els.card.classList.remove('hidden');els.title.textContent=active.title;els.channel.textContent=active.channel;els.thumb.src=active.thumb;let p=active.points,s=stats();els.current.textContent=fmt(p.at(-1)?.viewers);els.peak.textContent=fmt(s.peak);els.avg.textContent=fmt(s.avg);els.samples.textContent=`${p.length}点`;let a=p[0]?new Date(p[0].t).getTime():Date.now(),b=p.at(-1)?new Date(p.at(-1).t).getTime():a;els.elapsed.textContent=duration(b-a);draw()}
function draw(){let c=els.canvas,dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;let x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);let p=active?.points||[];if(p.length<1){x.fillStyle='#9299a8';x.font='14px sans-serif';x.fillText('データ取得待ち…',20,35);return}let vals=p.map(q=>q.viewers),min=Math.min(...vals),max=Math.max(...vals),pad=Math.max(1,(max-min)*.12),lo=Math.max(0,min-pad),hi=max+pad,L=52,R=14,T=18,B=32; x.strokeStyle='#252b38';x.fillStyle='#9299a8';x.font='11px sans-serif';for(let i=0;i<=4;i++){let yy=T+(h-T-B)*i/4;x.beginPath();x.moveTo(L,yy);x.lineTo(w-R,yy);x.stroke();let v=Math.round(hi-(hi-lo)*i/4);x.fillText(v.toLocaleString(),4,yy+4)}let t0=new Date(p[0].t).getTime(),t1=new Date(p.at(-1).t).getTime();if(t1===t0)t1=t0+1;x.strokeStyle='#ff385c';x.lineWidth=2.2;x.beginPath();p.forEach((q,i)=>{let xx=L+(new Date(q.t).getTime()-t0)/(t1-t0)*(w-L-R),yy=T+(hi-q.viewers)/(hi-lo||1)*(h-T-B);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke();x.fillStyle='#9299a8';x.fillText('0:00',L,h-10);x.fillText(duration(t1-t0).replace(/^0:/,''),Math.max(L,w-R-45),h-10)}
function renderHistory(){let logs=Object.values(load()).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));els.history.innerHTML=logs.length?'':'<p class="muted">まだ記録がありません。</p>';logs.forEach(l=>{let d=document.createElement('div');d.className='hist';let pk=l.points.length?Math.max(...l.points.map(x=>x.viewers)):null;d.innerHTML=`<div><strong>${esc(l.title)}</strong><span>${esc(l.channel)} · ${new Date(l.createdAt).toLocaleString('ja-JP')}</span></div><span>${l.points.length}点 / 最大 ${fmt(pk)}</span>`;d.onclick=()=>{active=l;render();els.status.textContent=l.endedAt?'終了':'履歴';els.status.classList.remove('live');scrollTo({top:els.card.offsetTop-10,behavior:'smooth'})};els.history.appendChild(d)})}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function download(type){if(!active)return;let blob,name;if(type==='json'){blob=new Blob([JSON.stringify(active,null,2)],{type:'application/json'});name=`${active.id}.json`}else{let rows=['timestamp,elapsed_seconds,concurrent_viewers'];let t0=active.points[0]?new Date(active.points[0].t).getTime():0;active.points.forEach(p=>rows.push(`${p.t},${Math.round((new Date(p.t).getTime()-t0)/1000)},${p.viewers}`));blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'});name=`${active.id}.csv`}let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
els.start.onclick=start;els.stop.onclick=()=>stop(true);els.precisionStart.onclick=startPrecision;els.precisionStop.onclick=stopPrecision;els.interval.onchange=()=>{localStorage.setItem('yt_interval',els.interval.value);updatePrecisionUI();if(timer&&precisionUntil<=Date.now())scheduleNext(0)};$('#csv').onclick=()=>download('csv');$('#json').onclick=()=>download('json');$('#clear').onclick=()=>{if(!active||!confirm('この記録を削除しますか？'))return;let x=load();delete x[active.id];saveAll(x);active=null;els.card.classList.add('hidden');renderHistory()};$('#deleteAll').onclick=()=>{if(confirm('すべての記録を削除しますか？')){localStorage.removeItem('live_logs');active=null;els.card.classList.add('hidden');renderHistory()}};document.addEventListener('visibilitychange',()=>{if(!document.hidden&&timer){tick().then(()=>scheduleNext());updatePrecisionUI()}});addEventListener('resize',()=>active&&draw());addEventListener('online',()=>els.net.textContent=timer?'記録中':'オンライン');addEventListener('offline',()=>els.net.textContent='オフライン');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});renderHistory();

updatePrecisionUI();updateQuota();
